apiVersion: v1
kind: Service
metadata:
  name: pytorch-master
  namespace: kubeflow
spec:
  clusterIP: None  # This makes it "headless"
  selector:
    training.kubeflow.org/job-role: master
    job-role: master
  ports:
    - protocol: TCP
      port: 23456
      targetPort: 23456
